version: '3'

services:
  app:
    image: ghcr.io/depau/house_inventory:main
    #build: .

    restart: unless-stopped

    volumes:
      - '/path/to/permanent/storage:/data'

    ports:
      - 127.0.0.1:8080:8080

    command: ["-w", "4", "-b", "0.0.0.0:8080"]
